---
title: "Econometriscs assignment"
author: "Heidi Marie Rolfsnes and Ann Elisabeth Jacobsen"
output:
  pdf_document: default
  html_document: default
---

```{r Packages}
suppressMessages(library(tidyverse))
suppressMessages(library(lubridate))
suppressMessages(library(tibble))
suppressMessages(library(readr))
suppressMessages(library(knitr))
suppressMessages(library(dplyr))
options(scipen = 999)
```

```{r GDP from Portugal, France, Hungary, Slovakia and Denmark}
BNP<- read.csv("nama_10r_3gdp.csv")
BNP <- BNP %>% 
  select(unit, geo, TIME_PERIOD, OBS_VALUE) %>%
      rename(GDP = "OBS_VALUE",Year = "TIME_PERIOD", Land = "geo") 
```

```{r  Population from Portugal, France, Hungary, Slovakia and Denmark}
Pop<- read_csv("demo_r_pjanaggr3.csv", show_col_types = FALSE)
Pop <- Pop %>% 
  select(geo, TIME_PERIOD, OBS_VALUE) %>%
      rename(Population = "OBS_VALUE",Year_pop = "TIME_PERIOD") 
 
  
```

```{r GNP and Population - together}
 BNP2<- BNP %>%
      select(unit, Land,Year, GDP) %>%
      left_join(Pop, by = c("Year" = "Year_pop", "Land" = "geo"))
     
```

```{r Calculate GDP per capita}
BNP2 <- BNP2 %>%
mutate(Per_capita =   GDP/Population*1000000) %>%
na.omit()
#NA variables are removed
```

```{r}
f
```

```{r Denmark}
DK <- group_by(BNP2, Land, Year) %>%
filter(Land "DK")
	summarise(DK, GDP_per_Capita = mean(Per_capita))
```

```{r}
Summary(DK)
```

```{r France}
FR <- group_by(BNP2, Land, Year) %>%
filter(Land == "FR")
	summarise(FR, GDP_per_Capita = mean(Per_capita))
```
```{r}
Summary(FR)
```

```{r Hungary}
HU <- group_by(BNP2, Land, Year) %>%
filter(Land == "HU")
	summarise(HU, GDP_per_Capita = mean(Per_capita))
```
```{r}
Summary(HU)
```

```{r Slovakia}
SK <- group_by(BNP2, Land, Year) %>%
filter(Land == "SK")
	summarise(SK, GDP_per_Capita = mean(Per_capita))
```
```{r}
Summary(SK)
```

```{r Portugal}
PT <- group_by(BNP2, Land, Year, Population, GDP) %>%
filter(Land == "PT")
	summarise(PT, GDP_per_Capita = mean(Per_capita))
```

```{r - denne må me endre}
summary(PT)
```




